### ISSUE TITLE
No public dns ...

### ISSUE THREAD

**Issue by swade1987** [the-startup-stack/stack-cookbooks#1]
When running your chef template, the server created doesn't get a public dns.
Note: I also have a tfvars file containing the access key, secret key and key_name values.
To reproduce this issue I ran the following commands

```
terraform get .
terraform plan
terraform apply

```

**Comment by KensoDev** [comment]
@swade1987 Solved by this commit: https://github.com/the-startup-stack/stack-cookbooks/commit/f2727833118f06d680ca99de61d1a12143231b84

All you need to do is pull the changes, go to `terraform/chef` and `terraform apply`.

**Comment by swade1987** [comment]
I re-ran the terraform template from scratch and still no luck. Note the VPC setup below ...

![image](https://cloud.githubusercontent.com/assets/594451/12787500/9a8c9eb4-ca8d-11e5-85b9-66a9a17cc974.png)

**Comment by swade1987** [comment]
perhaps in the terraform template for the VPC we need to set "enable_dns_hostnames" to "true" as its "false" by default

**Comment by KensoDev** [comment]
Look at the commit I referenced in my previous comment.
Did you `git pull` the repository? Look at `terraform/base`, you should have the `enable_dns_hostname` set to true.

**Comment by swade1987** [comment]
Sorry, my bad, I have just re-ran the script and it looks much better.
Just hoping I can access the chef server using the public DNS address now, will update you shortly.

**Comment by KensoDev** [comment]
You will be able to. The problem is you will still need to install an SSL certificate.

**Comment by swade1987** [comment]
can i not bypass that by doing "knife ssl fetch" to get the .crt file from the server itself?

**Comment by KensoDev** [comment]
Even then, I am not sure it will work properly with all the commands.
If you can give that a try and let me know here, it would be great.

**Comment by swade1987** [comment]
That doesn't work, I think I need to create a certificate file which matches the DNS hostname of the machine, is that the way you set yours up?

**Comment by KensoDev** [comment]
Yes. 
It's mentioned here.
http://docs.the-startup-stack.com/bootstrapping/install-chef-server/#production-use

Since chef server is using SSL, the setup on it is a bit more complicated than the other parts of the stack. There's really no easier way around it that I know of. Other than using the SAAS version.

**Comment by swade1987** [comment]
Makes sense, I will give that a go remotely from home and let you know how I get on.

**Comment by KensoDev** [comment]
@swade1987 Can you confirm this is fixed for you after the recent changes?

**Comment by swade1987** [comment]
Yes fixed.

Regards

Steven

Sent from my iPhone

On 10 Feb 2016, at 01:27, Avi Tzurel <notifications@github.com<mailto:notifications@github.com>> wrote:

@swade1987https://github.com/swade1987 Can you confirm this is fixed for you after the recent changes?

##
